### ISSUE TITLE
AASet nth not-found option

### ISSUE THREAD

**Issue by miner** [laforge49/aatree#45]
The AASet -nth doesn't work with the not-found option.  I think the fix would be more like the AAMap implementation.  First example below works as expected; the second fails mysteriously.

```
(nth (conj (aa/new-sorted-set (aa/basic-opts)) 1 2 3) 2 :not-found)
3

(nth (conj (aa/new-sorted-set (aa/basic-opts)) 1 2 3) 4 :not-found)
ClassCastException   [trace missing]
```

**Comment by laforge49** [comment]
The bug in AASet is obvious on inspection:

(defn -nth
  ([^AASet this var1](let [^AAMap mpl %28.-impl this%29
         ^MapEntry e %28.nth mpl var1%29]
     %28.getKey e%29))
  ([^AASet this var1 var2](let [^AAMap mpl %28.-impl this%29
         ^MapEntry e %28.nth mpl var1 var2%29]
     %28.getKey e%29)))

The cast exception occurs because :not-found is not a MapEntry.

We need an identity check before doing the getKey.

**Comment by laforge49** [comment]
Reproduced error:

ERROR in (nth-of-set) (AASet.clj:86)
expected: (= :not-found (nth (conj (new-sorted-set (basic-opts)) 1 2 3) 4 :not-found))
  actual: java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.MapEntry
 at aatree.AASet$_nth.invoke (AASet.clj:86)
    aatree.AASet.nth (:-1)
    clojure.lang.RT.nth (RT.java:881)
    aatree.core_test/fn (core_test.clj:174)

**Comment by laforge49** [comment]
The fixed function:

(defn -nth
  ([^AASet this var1](let [^AAMap mpl %28.-impl this%29
         ^MapEntry e %28.nth mpl var1%29]
     %28.getKey e%29))
  ([^AASet this var1 var2](let [^AAMap mpl %28.-impl this%29
         n %28.nth mpl var1 var2%29]
     %28if %28identical? var2 n%29
       n
       %28key n%29%29)))

Pushed.

0.6.2-SNAPSHOT deployed

**Comment by miner** [comment]
Works for me now.  Thanks.
